/*CTE'S practice problems*/


/*1. Display total revenue generated by each customer.*/
WITH customer_revenue AS
(
SELECT 
	customer_id,
	SUM(total_amount) AS revenue
FROM orders
GROUP BY customer_id
)

SELECT *
FROM customer_revenue;


/*2. Find customers whose revenue is greater than ₹10,000.*/

WITH customer_revenue AS
(
SELECT
	customer_id,
	SUM(total_amount) AS revenue
FROM orders
GROUP BY customer_id
)

SELECT *
FROM customer_revenue
WHERE revenue > 10000;


/*3. Find the customer with the highest revenue.*/

WITH customer_revenue as
(
SELECT 
	customer_id,
	sum(total_amount) As revenue
FROM orders
GROUP BY customer_id
)
SELECT *
FROM customer_revenue 
ORDER BY revenue DESC
LIMIT 1;


/*4. Calculate revenue generated by each store.*/

WITH store_revenue AS
(
SELECT
	store_id,
	sum(total_amount) as revenue
from orders
group by store_id
)
select *
from store_revenue;


/*5. Find stores earning above the average store revenue.*/

WITH store_revenue as 
(
SELECT 
	store_id,
    sum(total_amount)  as revenue
FROM orders
group by store_id
)
select * 
from store_revenue
where revenue>
(
	select avg(revenue)
	from store_revenue
);


/*6. Calculate total orders handled by each employee.*/

WITH employee_orders AS
(
    SELECT
        employee_id,
        COUNT(*) total_orders
    FROM orders
    GROUP BY employee_id
)

SELECT *
FROM employee_orders;


/*7. Find employees handling more than 15 orders.*/

WITH employee_orders AS
(
    SELECT
        employee_id,
        COUNT(*) total_orders
    FROM orders
    GROUP BY employee_id
)

SELECT *
FROM employee_orders
WHERE total_orders > 15;


/*8. Find customers whose average order value exceeds ₹2,000.*/

WITH avg_customer_order AS
(
    SELECT
        customer_id,
        AVG(total_amount) avg_order
    FROM orders
    GROUP BY customer_id
)

SELECT *
FROM avg_customer_order
WHERE avg_order > 2000;


/*10. Calculate quantity sold for each product.*/


WITH product_sales AS
(
    SELECT
        product_id,
        SUM(quantity) quantity_sold
    FROM order_items
    GROUP BY product_id
)

SELECT *
FROM product_sales;


/*11. Find the highest-selling product.*/

with product_sales as
(
select 
	product_id,
	sum(quantity) as quantity_sold
from order_items
group by product_id
)

select *
from product_sales
order by quantity_sold desc 
limit 1;


/*12. Find products generating revenue above the average.*/

WITH product_revenue as
(
SELECT 
	product_id,
    sum(quantity * unit_price) as revenue
from order_items
group by product_id
)

select *
from product_revenue
where revenue >
(
  select avg(revenue)
  from product_revenue
);


/*13. Calculate revenue generated by each product.*/

WITH product_revenue AS
(
    SELECT
        product_id,
        SUM(quantity * unit_price) revenue
    FROM order_items
    GROUP BY product_id
)

SELECT *
FROM product_revenue;


/*14. Find total revenue by city.*/

with city_revenue AS
(
select 
	c.city,
    sum(o.total_amount) as revenue
from customers as c
join orders o on c.customer_id = o.customer_id
group by c.city
)

select *
from city_revenue;


/*15. Count orders placed by each customer.*/

with customer_orders as
(
select 
	customer_id,
	count(*) total_orders
from orders
group by customer_id
) 

select * 
from customer_orders;

/*17. Find customers placing more than five orders.*/

with customer_orders as
(
select 	
	customer_id,
    count(*) total_orders
from orders
group by customer_id
)
select *
from customer_orders
where total_orders > 5;

/*18. Calculate total revenue handled by each manager.*/

with manager_revenue as
(
select
	m.employee_name,
    sum(o.total_amount) as revenue
from employees m
join employees e on m.employee_id = e.manager_id
join orders o on e.employee_id = o.employee_id
group by m.employee_name
)
select * 
from manager_revenue;


/*9. Find managers whose teams generated above-average revenue.*/

WITH manager_revenue AS
(
    SELECT
        m.employee_name,
        SUM(o.total_amount) revenue
    FROM employees m
    JOIN employees e
        ON m.employee_id = e.manager_id
    JOIN orders o
        ON e.employee_id = o.employee_id
    GROUP BY m.employee_name
)

SELECT *
FROM manager_revenue
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM manager_revenue
);


/*20. Find stores contributing to the top 50% of total revenue.*/


WITH store_revenue AS
(
    SELECT
        store_id,
        SUM(total_amount) revenue
    FROM orders
    GROUP BY store_id
)

SELECT *
FROM store_revenue
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM store_revenue
);