/* Aggregation Functions practice, 1. Count */

/*1. Count total orders placed by each customer. (INNER JOIN)*/

SELECT 
	c.customer_id,
    c.first_name,
    COUNT(o.order_id) AS total_orders
FROM 
	customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY
	c.customer_id,
    c.first_name;
    
    
/* 2. Count all customers including those with no orders. (LEFT JOIN) */  

SELECT 
	c.customer_id,
    c.first_name,
    SUM(o.order_id) AS total_orders
FROM 
	customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY
	c.customer_id,
    c.first_name;   
    

/*3. Count products sold in each order.*/


SELECT
    o.order_id,
    COUNT(oi.product_id) AS total_products
FROM orders o
INNER JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY o.order_id;




/* 4. Count employees working under each manager. (LEFT JOIN).*/


SELECT 
	m.employee_name AS Manager,
    COUNT(e.employee_id) AS Employees
FROM 
	employees AS m
LEFT JOIN employees AS e on m.employee_id = e.manager_id
GROUP BY 
	m.employee_name;


/*5. Count orders received by each store*/


SELECT
	s.store_name,
    COUNT(o.order_id) AS total_orders
FROM stores AS s
LEFT JOIN orders AS o ON s.store_id = o.store_id
GROUP BY s.store_name;


/* SUM Practice Questions */

/*6. Total revenue generated by each customer.*/

SELECT 
	c.customer_id,
    c.first_name,
    SUM(o.total_amount) AS revenue
FROM 
	customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY
	c.customer_id,
    c.first_name;


/*7. Revenue generated by each store.*/

SELECT
	s.store_name,
    SUM(o.total_amount) AS total_revenue
FROM stores AS s
LEFT JOIN orders AS o ON s.store_id = o.store_id
GROUP BY s.store_name;



/*8. Total quantity sold for each product.*/


SELECT 
	p.product_name,
	SUM(oi.quantity) as quantity_sold
FROM products p
JOIN order_items as oi on p.product_id = oi.product_id
GROUP BY p.product_name;



/*9. Revenue generated by each employee.*/


SELECT 
	e.employee_name,
    SUM(o.total_amount) AS revenue
FROM employees e
JOin orders o on e.employee_id = o.employee_id
GROUP BY e.employee_id;



/*10. Revenue generated by each manager. (SELF JOIN)*/    


SELECT 
	m.employee_name,
    SUM(o.total_amount) AS revenue
FROM employees m
join employees e on m.employee_id = e.manager_id
join orders o on e.employee_id = o.employee_id
GROUP BY m.employee_name;
	


/*AVG Functions*/


/*11. Average order value for each customer.*/


SELECT 
	c.first_name,
    AVG(o.total_amount) as AVG_order
FROM customers c
join orders o on c.customer_id = o.customer_id
GROUP BY c.first_name;





/*12. Average revenue per employee.*/


select 
	e.employee_name,
    avg(o.total_amount) as total_revenue
FROM employees e
join orders o on e.employee_id = o.employee_id
group by e.employee_name;


/*13 Average product price by category.*/


select
	category,
    avg(price)
FROM products
GROUP BY category;


/*14. Average quantity sold for each product.*/


SELECT 
	category,
	p.product_name,
    AVG(oi.quantity) as Average_q
FROM products p
join order_items oi on p.product_id = oi.product_id
GROUP BY p.product_name;


/*15. Average order value by store.*/


select 
	s.store_name,
    avg(o.total_amount) as total_amount
from stores s
join orders o on s.store_id = o.store_id
group by s.store_name;


/*MIN Queries*/


/*16. Smallest order for each customer.*/



select 
	c.first_name,
	min(o.total_amount) as t
from customers c
join orders o on c.customer_id = o.customer_id
group by c.first_name;



/*17. Cheapest product sold. */


SELECT
    p.product_name,
    MIN(oi.unit_price)
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name;


/*18. Minimum sale handled by each employee.*/


SELECT
    e.employee_name,
    MIN(o.total_amount)
FROM employees e
JOIN orders o
ON e.employee_id = o.employee_id
GROUP BY e.employee_name;


/*19. Manager with minimum team revenue. (SELF JOIN)*/


SELECT
    m.employee_name,
    MIN(o.total_amount) as mn
FROM employees m
JOIN employees e
ON m.employee_id = e.manager_id
JOIN orders o
ON e.employee_id = o.employee_id
GROUP BY m.employee_name;


/*MAX*/


/*21. Highest order placed by each customer.*/

SELECT
    c.first_name,
    MAX(o.total_amount) as m
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.first_name;



/*22. Most expensive product sold.*/

SELECT
    p.product_name,
    MAX(oi.unit_price) as maxim
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name;


/*23. Highest sale by employee.*/


select 
	e.employee_name,
    max(o.total_amount)  hse
from employees as e
join orders o on e.employee_id = o.employee_id
group by e.employee_name;



/*24. Highest order received by each store.*/


select
	s.store_name,
	max(o.total_amount) horbes
from stores s
join orders o on s.store_id = o.store_id
group by s.store_name;



/*25. Manager whose team achieved the highest single order.*/


select
	m.employee_name,
    max(o.total_amount) as mwtathso
from employees m
join employees e on m.employee_id = e.manager_id
join orders o on e.employee_id = o.employee_id
group by m.employee_name;